# Site Configuration

# Basic site information
title = "Simpleminded Robot"
baseurl = "http://simpleminded.bot/"
canonifyURLs = true  # Converts all relative URLs to absolute URLs
disableAliases = true  # Disables generation of alias redirects
disableHugoGeneratorInject = true  # Removes Hugo generator meta tag
# disableKinds = ["taxonomy", "term"]  # Uncomment to disable taxonomy and term pages
enableEmoji = true  # Enables emoji support in content
enableGitInfo = false  # Disables Git commit information
enableRobotsTXT = true  # Generates a robots.txt file
languageCode = "en-US"  # Sets the language code for the site
# paginate = 10  # Uncomment to set number of items per page in lists
pagination.pagerSize = 10  # Number of pagination links to display
rssLimit = 10  # Limit of items in RSS feed
summarylength = 70  # Length of automatic page summaries
timeout = "60s"  # Build timeout

# Site description for SEO
description = "AI and Agile Development Insights | Explore AI integration, Agile workflows, and tech advancements in software development."

# Multilingual settings
defaultContentLanguage = "en"  # Default content language
disableLanguages = ["de", "nl"]  # Disabled languages
defaultContentLanguageInSubdir = false  # Don't put default language in subdirectory

# Copyright notice
copyright = "<a class='text-muted' href='https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>"

# Build configuration
[build]
  buildStats.enable = true  # Enables build statistics

# Output formats configuration
[outputs]
  home = ["HTML", "RSS", "searchIndex"]  # Output formats for home page
  section = ["HTML", "RSS", "SITEMAP"]  # Output formats for sections

# Custom output format for search index
[outputFormats.searchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true

# Custom output format for section sitemap
[outputFormats.SITEMAP]
  mediaType = "application/xml"
  baseName = "sitemap"
  isHTML = false
  isPlainText = true
  noUgly = true
  rel  = "sitemap"

# Sitemap configuration
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Caching configuration
[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "30m"
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"

# Taxonomy configuration
[taxonomies]
  contributor = "contributors"
  category = "categories"
  tag = "tags"
  series = "series"

# URL structure configuration
[permalinks]
  blog = "/blog/:slug/"
  docs = "/docs/:sections[1:]/:slug/"

# Minification configuration
[minify]
  minifyOutput = true  # Enables minification of output

  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 1
    [minify.tdewolff.js]
      precision = 1
      keepVarNames = false

# Related content configuration
[related]
  threshold = 80
  includeNewer = true
  toLower = true
    [[related.indices]]
      name = "series"
      weight = 100
    [[related.indices]]
      name = "tags"
      weight = 80
    [[related.indices]]
      name = "date"
      weight = 10

# Image processing configuration
[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 85
  resampleFilter = "Lanczos"

[imaging.exif]
  disableDate = false
  disableLatLong = true
  includeFields = ""
  excludeFields = ""

# Server configuration
[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Cache-Control = "public, max-age=31536000"

# Asset processing configuration
[assets]
  fingerprint = true
