# Hugo basic site parameters
title = "Simpleminded Robot"
description = "Discover how AI is transforming Agile development practices. Explore tech trends, project management insights, and innovative solutions for modern software development."
images = ["cover.png"]  # Default image for social sharing and SEO

# Main sections to be considered for content organization
mainSections = ["docs"]

# Social media settings
[social]
  twitter = ""  # Twitter handle (if applicable)

# Doks theme configuration (@thulite/doks-core)
[doks]
  # Color mode settings
  colorMode = "light" # Options: auto (default), light, or dark
  colorModeToggler = true # Enable/disable color mode toggle (only relevant when colorMode = auto)

  # Navbar settings
  navbarSticky = true # Make navbar sticky (true by default)
  containerBreakpoint = "xxl" # Navbar container breakpoint: "", "sm", "md", "lg" (default), "xl", "xxl", or "fluid"

  # Navbar button settings
  navBarButton = false # Show/hide navbar button (false by default)
  navBarButtonUrl = "/docs/prologue/introduction/"  # URL for navbar button
  navBarButtonText = "Get started"  # Text for navbar button

  # Search settings
  flexSearch = true # Enable/disable FlexSearch (true by default)
  searchExclKinds = [] # Page kinds to exclude from search indexing
  searchExclTypes = [] # Content types to exclude from search indexing
  showSearch = [] # Sections to show search (empty array means all pages)
  indexSummary = false # Index only summary instead of full content (false by default)

  # Search results display settings
  showDate = false # Show date in search results (false by default)
  showSummary = true # Show summary in search results (true by default)
  searchLimit = 99 # Limit for search results (0 means no limit)

  # Global alert settings
  alert = false # Show/hide global alert (false by default)
  alertDismissable = true # Make alert dismissable (true by default)

  # Bootstrap JavaScript
  bootstrapJavascript = false # Include Bootstrap JavaScript (false by default)

  # Navigation settings
  sectionNav = ["docs"] # Sections to include in navigation
  toTopButton = true # Show/hide "to top" button (false by default)
  breadcrumbTrail = true # Show/hide breadcrumb trail (false by default)
  headlineHash = true # Enable/disable headline hash links (true by default)
  scrollSpy = true # Enable/disable scroll spy for navigation (true by default)

  # Multilingual settings
  multilingualMode = false # Enable/disable multilingual mode (false by default)
  showMissingLanguages = false # Show/hide untranslated languages in language menu (true by default)

  # Versioning settings
  docsVersioning = false # Enable/disable docs versioning (false by default)
  docsVersion = "1.0"  # Current docs version

  # UX settings
  headerBar = true # Show/hide header bar (true by default)
  backgroundDots = false # Show/hide background dots (true by default)

  # Homepage settings
  sectionFooter = true # Show/hide section footer on homepage (false by default)

  # Blog settings
  relatedPosts = true # Show/hide related posts (false by default)
  imageList = true # Show/hide images in post lists (true by default)
  imageSingle = true # Show/hide images in single posts (true by default)

  # Table of Contents settings
  toc = true # Enable/disable Table of Contents (false by default)
  tocStartLevel = 2 # Starting heading level for ToC (2 by default)
  tocEndLevel = 3 # Ending heading level for ToC (3 by default)

  # Repository settings
  editPage = false # Enable/disable "Edit this page" links (false by default)
  lastMod = false # Show/hide last modified date (false by default)
  repoHost = "GitHub" # Repository host: GitHub (default), Gitea, GitLab, Bitbucket, or BitbucketServer
  docsRepo = "https://github.com/h-enk/doks"  # URL of the docs repository
  docsRepoBranch = "main" # Branch name of the docs repository
  docsRepoSubPath = "" # Subpath within the repository for docs

  # SCSS color customization (commented out by default)
  # backGround = "yellowgreen"
  ## Dark theme colors
  # textDark = "#dee2e6"
  # accentDark = "#5d2f86"
  ## Light theme colors
  # textLight = "#1d2d35"
  # accentLight = "#8ed6fb"

  # Menu settings (commented out by default)
  # [doks.menu]
  #   [doks.menu.section]
  #     auto = true # Automatically generate section menu (true by default)
  #     collapsibleSidebar = true # Make sidebar collapsible (true by default)

# Debug settings for render hooks
[render_hooks.image]
  errorLevel = 'ignore' # Error level for image rendering: ignore (default), warning, or error

[render_hooks.link]
  errorLevel = 'ignore' # Error level for link rendering: ignore (default), warning, or error
  highlightBroken = false # Highlight broken links (false by default)

# Image processing settings (@thulite/images)
[thulite_images]
  [thulite_images.defaults]
    decoding = "async" # Image decoding: sync, async, or auto (default)
    fetchpriority = "auto" # Fetch priority: high, low, or auto (default)
    loading = "lazy" # Image loading: eager or lazy (default)
    widths = [480, 576, 768, 1025, 1200, 1440] # Responsive image widths
    sizes = "auto" # Responsive image sizes: 100vw (default), 75vw, or auto
    process = "" # Image processing commands
    lqip = "16x webp q20" # Low-quality image placeholder settings

# Inline SVG settings (@thulite/inline-svg)
[inline_svg]
  iconSetDir = "tabler-icons" # Directory for icon set ("tabler-icons" by default)

# SEO settings (@thulite/seo)
[seo]
  [seo.title]
    separator = " | "  # Separator for page titles
    suffix = ""  # Suffix for page titles
  [seo.favicons]
    sizes = [16, 32, 96, 192]  # Favicon sizes
    icon = "img/favicon/favicon-32x32.png"  # Default favicon
    svgIcon = "img/favicon/favicon.svg"  # SVG favicon
    maskIcon = "img/favicon/safari-pinned-tab.svg"  # Safari mask icon
    maskIconColor = "#5bbad5"  # Color for Safari mask icon

  # Schema settings (commented out by default)
  # [seo.schemas]
  #   type = "Organization" # Schema type: Organization (default) or Person
  #   logo = "assets/img/favicon/android-chrome-512x512.png"  # Organization logo
  #   name = "Simpleminded Robot" # Name of Organization or Person
  #   sameAs = [] # Social media and other links
  #   images = ["cover.png"] # Default images for schema
  #   article = [] # Article schema sections
  #   newsArticle = [] # NewsArticle schema sections
  #   blogPosting = ["blog"] # BlogPosting schema sections
  #   product = [] # Product schema sections
